# Generated by Django 5.2.1 on 2025-05-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailylogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylogs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grievances',
            options={},
        ),
        migrations.AlterModelOptions(
            name='monthlyratings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partnerinvitations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
