# Generated by Django 5.2.1 on 2025-05-24 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dailylogs_options_alter_grievances_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylogs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grievances',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='monthlyratings',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='partnerinvitations',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
